CREATE TABLE users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(255) NOT NULL UNIQUE,
    alt_phone VARCHAR(255) NULL,
    role ENUM('SME', 'TA', 'ADMIN') NOT NULL,
    gender ENUM('Male', 'Female', 'Other') NOT NULL,
    bank_name VARCHAR(255) NOT NULL,
    bank_ac_no VARCHAR(20) NOT NULL UNIQUE,
    bank_ifsc VARCHAR(255) NOT NULL,
    bank_address VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
